### ISSUE TITLE
Implementar Banco de Dados

### ISSUE THREAD

**Issue by EsdrasPedro** [Robert-081/MundoOrganico#1]
- [x] Criar modelo
- [x] Definir possíveis relacionamentos das entidade
- [x] Criar Modelo físico
- [x] Criar Modelo Lógico
